[build]
builder = "dockerfile"

[deploy]
startCommand = "python app.py"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments]
[environments.production]
FLASK_ENV = "production"
SECRET_KEY = "sme-debt-tool-production-secret-key-2025"
PORT = "5000"
