[build]
builder = "dockerfile"

[deploy]
startCommand = "/app/start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments]
[environments.production]
FLASK_ENV = "production"
SECRET_KEY = "sme-debt-tool-production-secret-key-2025"
PORT = "5000"
PYTHONUNBUFFERED = "1"
